[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "MindRef"
version = "0.5.2"
description = "Cross-Platform Application for maintaining Markdown formatted notes"
readme = "README.md"
requires-python = ">=3.11"
license = { text = "LGPLv3+" }
authors = [
    { name = "Eric Stasney", email = "estasney@users.noreply.github.com" }
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.12",
    "License :: OSI Approved :: GNU Lesser General Public License v3 or later (LGPLv3+)",
]
urls = { "Homepage" = "https://github.com/estasney/MindRef" }

dependencies = [
    "Kivy==2.3.1",
    "mistune==2.0.5",
    "pillow<11.1.0",
    "Pygments==2.19.0",
    "python-dotenv==1.0.1",
    "toolz>=1,<2",
]

[project.scripts]
mindref = "mindref.main:main"


[dependency-groups]
dev = [
    "click>=8.1.8",
    "colour>=0.1.5",
    "cython>3,<=3.0.11",
    "line-profiler>=4.2.0",
    "pre-commit>=4.1.0",
    "pytest>=8.4.1",
    "ruff>=0.15.22",
]

android = [
    "pyjnius==1.6.1",
    "python-for-android==2026.5.9",
]

[tool.setuptools]
ext-modules = [
    { name = "mindref.lib.ext.ext", sources = ["src/mindref/lib/ext/ext.c"] }
]
include-package-data = true
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"mindref" = [
    "assets/*",
]

[tool.uv]
package = true

[tool.ruff]
target-version = "py312"
[tool.ruff.lint]
select = [
    "A",
    "ANN",
    "ASYNC",
    "B",
    "BLE",
    "C4",
    "DTZ",
    "ERA",
    "F",
    "FA",
    "FAST",
    "FLY",
    "FURB",
    "I",
    "INP",
    "N",
    "NPY",
    "PD",
    "PERF",
    "PIE",
    "PLC0105",
    "PLC0131",
    "PLC0132",
    "PLC0207",
    "PLC0208",
    "PLE",
    "PLR",
    "PLW",
    "PYI",
    "RET",
    "RUF",
    "SIM",
    "TRY",
    "UP",
    "YTT",
]
ignore = [
    "A002",
    "ANN002",
    "ANN003",
    "ANN202",
    "ANN401",
    "N818",
    "PLR0912",
    "PLR0913",
    "PLR0915",
    "PLR2004",
    "RET504",
    "RUF001",
    "TRY003",
]

[tool.ruff.lint.flake8-annotations]
ignore-fully-untyped = true
suppress-dummy-args = true

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401", "I001"]
"**/android/**/*.py" = ["N"]
"**/*.pyi" = ["ALL"]
"p4a-recipes/**/*.py" = ["N"]
"scripts/**/*.py" = ["INP"] 

[[tool.ty.overrides]]
include = ["stubs/**"]

[tool.ty.overrides.rules]
unresolved-reference = "ignore"
unresolved-import = "ignore"

[tool.ty.environment]
extra-paths=["./stubs"]

