#:import seps mindref.lib.widgets.separator
#:import style mindref.lib.widgets.style
<ThemedButton>:
    background_normal: app.atlas_service.uri_for("bg_normal", atlas_name="textures") if max(self.border) > 0 else app.atlas_service.uri_for("bg_normal_nb", atlas_name="textures")
    background_down: app.atlas_service.uri_for("bg_down", atlas_name="textures") if max(self.border) > 0 else app.atlas_service.uri_for("bg_down_nb", atlas_name="textures")
    background_disabled: app.atlas_service.uri_for("bg_disabled", atlas_name="textures") if max(self.border) > 0 else app.atlas_service.uri_for("bg_disabled_nb", atlas_name="textures")
    state_image: self.background_normal if self.state == 'normal' else self.background_down
    disabled_image: self.background_disabled
    orientation: 'vertical'
    border: dp(8)
    padding: dp(5)
    spacing: dp(2)
    canvas:
        Color:
            rgba: self.background_color
        BorderImage:
            border:  self.border
            pos: self.pos
            size: self.size
            source: self.state_image if not self.disabled else self.disabled_image

<ThemedLabelButton@ThemedButton>:
    text: ''
    size_hint_y: None
    height: self.minimum_height
    canvas:
        Color:
            rgba: self.background_color
        BorderImage:
            border:  self.border
            pos: self.pos
            size: self.size
            source: self.state_image if not root.disabled else self.disabled_image
    BaseLabel:
        text: root.text
        size_hint_y: None
        height: self.texture_size[1] * 2
        color: root.color
        
<ContainedLabelButton@ThemedLabelButton>:
    disable_ripple_effect: True
    background_color: (0,0,0,0)
    canvas:
        Color:
            rgba: self.color       
        Line:
            rounded_rectangle: self.x, self.y, self.width, self.height, dp(8)
            width: dp(1)
            
<LabelButton@ThemedLabelButton>:
    disable_ripple_effect: True
    background_color: (0,0,0,0)            
        


<ThemedIconButton@ThemedLabelButton>:
    icon_code: ''
    icon_size: sp(app.base_font_size + 10)
    orientation: 'vertical'
    size_hint_y: None
    height: self.minimum_height
    canvas:
        Color:
            rgba: self.background_color
        BorderImage:
            border:  self.border
            pos: self.pos
            size: self.size
            source: self.state_image if not root.disabled else self.disabled_image
    IconLabel:
        id: icon
        icon_code: root.icon_code
        font_size: root.icon_size
        text_size: self.size
        size: self.texture_size
        valign: 'middle'
        halign: 'center'
        size_hint: None, None
        pos_hint: {"center_x": .5, "center_y": .5}
        color: root.color

<-ImageButton>:
    state_image: self.background_normal if self.state == 'normal' else self.background_down
    background_color: app.colors['Primary'] if self.state == 'normal' else app.colors['Accent-One']
    orientation: 'vertical'
    padding: dp(5)
    spacing: dp(2)

    canvas:
        Color:
            rgba: self.background_color
        BorderImage:
            border:  [dp(8), dp(8), dp(8), dp(8)]
            pos: self.pos
            size: self.size
            source: root.state_image if not root.disabled else root.background_disabled

    Image:
        mipmap: True
        source: root.source



<SaveButton@ThemedIconButton>:
    icon_code: '\ue161'
<CancelButton@ThemedIconButton>:
    icon_code: '\ue5c9'
<OpenSettingsButton@ThemedIconButton>:
    icon_code: '\ue8b9'
    background_color: (0,0,0,0)
    color: (1.0, 1.0, 1.0, 0.5)
