"""
Hand-written stub. `kivy.graphics.context_instructions` is a compiled Cython
module, so pyright's stub generator had no source to read. Signatures follow the
kivy 2.3.1 sources in `.claude/kivy`.

Matrix and texture values are `Any` because `kivy.graphics.transformation` and
`kivy.graphics.texture` are themselves unstubbed compiled modules. Geometry
properties are `Sequence[float]` on both sides: the getters return tuples, the
setters take any sequence of the right length.
"""

from collections.abc import Sequence
from typing import Any, overload

from kivy.graphics.instructions import ContextInstruction

__all__ = (
    "Color",
    "BindTexture",
    "PushMatrix",
    "PopMatrix",
    "Rotate",
    "Scale",
    "Translate",
    "MatrixInstruction",
    "gl_init_resources",
)

def gl_init_resources() -> None: ...

class PushState(ContextInstruction):
    def __init__(self, *args: str, **kwargs: Any) -> None: ...
    @property
    def state(self) -> str: ...
    @state.setter
    def state(self, value: str) -> None: ...
    @property
    def states(self) -> list[str]: ...
    @states.setter
    def states(self, value: list[str]) -> None: ...

class ChangeState(ContextInstruction):
    @property
    def changes(self) -> dict[str, Any]: ...
    @changes.setter
    def changes(self, value: dict[str, Any]) -> None: ...

class PopState(ContextInstruction):
    def __init__(self, *args: str, **kwargs: Any) -> None: ...
    @property
    def state(self) -> str: ...
    @state.setter
    def state(self, value: str) -> None: ...
    @property
    def states(self) -> list[str]: ...
    @states.setter
    def states(self, value: list[str]) -> None: ...

class Color(ContextInstruction):
    @overload
    def __init__(self, **kwargs: Any) -> None: ...
    @overload
    def __init__(self, r: float, g: float, b: float, /, **kwargs: Any) -> None: ...
    @overload
    def __init__(
        self, r: float, g: float, b: float, a: float, /, **kwargs: Any
    ) -> None: ...
    @property
    def rgba(self) -> Sequence[float]: ...
    @rgba.setter
    def rgba(self, value: Sequence[float]) -> None: ...
    @property
    def rgb(self) -> Sequence[float]: ...
    @rgb.setter
    def rgb(self, value: Sequence[float]) -> None: ...
    @property
    def hsv(self) -> Sequence[float]: ...
    @hsv.setter
    def hsv(self, value: Sequence[float]) -> None: ...
    @property
    def r(self) -> float: ...
    @r.setter
    def r(self, value: float) -> None: ...
    @property
    def g(self) -> float: ...
    @g.setter
    def g(self, value: float) -> None: ...
    @property
    def b(self) -> float: ...
    @b.setter
    def b(self, value: float) -> None: ...
    @property
    def a(self) -> float: ...
    @a.setter
    def a(self, value: float) -> None: ...
    @property
    def h(self) -> float: ...
    @h.setter
    def h(self, value: float) -> None: ...
    @property
    def s(self) -> float: ...
    @s.setter
    def s(self, value: float) -> None: ...
    @property
    def v(self) -> float: ...
    @v.setter
    def v(self, value: float) -> None: ...

class BindTexture(ContextInstruction):
    @property
    def texture(self) -> Any: ...
    @texture.setter
    def texture(self, value: Any) -> None: ...
    @property
    def index(self) -> int: ...
    @index.setter
    def index(self, value: int) -> None: ...
    @property
    def source(self) -> str | None: ...
    @source.setter
    def source(self, value: str | None) -> None: ...

class LoadIdentity(ContextInstruction):
    @property
    def stack(self) -> str: ...
    @stack.setter
    def stack(self, value: str) -> None: ...

class PushMatrix(ContextInstruction):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    @property
    def stack(self) -> str: ...
    @stack.setter
    def stack(self, value: str) -> None: ...

class PopMatrix(ContextInstruction):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    @property
    def stack(self) -> str: ...
    @stack.setter
    def stack(self, value: str) -> None: ...

class ApplyContextMatrix(ContextInstruction):
    @property
    def target_stack(self) -> str: ...
    @target_stack.setter
    def target_stack(self, value: str) -> None: ...
    @property
    def source_stack(self) -> str: ...
    @source_stack.setter
    def source_stack(self, value: str) -> None: ...

class UpdateNormalMatrix(ContextInstruction): ...

class MatrixInstruction(ContextInstruction):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    @property
    def matrix(self) -> Any: ...
    @matrix.setter
    def matrix(self, value: Any) -> None: ...
    @property
    def stack(self) -> str: ...
    @stack.setter
    def stack(self, value: str) -> None: ...

class Transform(MatrixInstruction):
    def transform(self, trans: Any) -> None: ...
    def translate(self, tx: float, ty: float, tz: float) -> None: ...
    def rotate(self, angle: float, ax: float, ay: float, az: float) -> None: ...
    def scale(self, s: float) -> None: ...
    def identity(self) -> None: ...

class Rotate(Transform):
    @overload
    def __init__(self, **kwargs: Any) -> None: ...
    @overload
    def __init__(
        self, angle: float, ax: float, ay: float, az: float, /, **kwargs: Any
    ) -> None: ...
    def set(self, angle: float, ax: float, ay: float, az: float) -> None: ...
    @property
    def angle(self) -> float: ...
    @angle.setter
    def angle(self, value: float) -> None: ...
    @property
    def axis(self) -> Sequence[float]: ...
    @axis.setter
    def axis(self, value: Sequence[float]) -> None: ...
    @property
    def origin(self) -> Sequence[float]: ...
    @origin.setter
    def origin(self, value: Sequence[float]) -> None: ...

class Scale(Transform):
    @overload
    def __init__(self, **kwargs: Any) -> None: ...
    @overload
    def __init__(self, x: float, y: float, z: float, /, **kwargs: Any) -> None: ...
    @property
    def x(self) -> float: ...
    @x.setter
    def x(self, value: float) -> None: ...
    @property
    def y(self) -> float: ...
    @y.setter
    def y(self, value: float) -> None: ...
    @property
    def z(self) -> float: ...
    @z.setter
    def z(self, value: float) -> None: ...
    @property
    def xyz(self) -> Sequence[float]: ...
    @xyz.setter
    def xyz(self, value: Sequence[float]) -> None: ...
    @property
    def origin(self) -> Sequence[float]: ...
    @origin.setter
    def origin(self, value: Sequence[float]) -> None: ...

class Translate(Transform):
    @overload
    def __init__(self, **kwargs: Any) -> None: ...
    @overload
    def __init__(self, x: float, y: float, /, **kwargs: Any) -> None: ...
    @overload
    def __init__(self, x: float, y: float, z: float, /, **kwargs: Any) -> None: ...
    @property
    def x(self) -> float: ...
    @x.setter
    def x(self, value: float) -> None: ...
    @property
    def y(self) -> float: ...
    @y.setter
    def y(self, value: float) -> None: ...
    @property
    def z(self) -> float: ...
    @z.setter
    def z(self, value: float) -> None: ...
    @property
    def xy(self) -> Sequence[float]: ...
    @xy.setter
    def xy(self, value: Sequence[float]) -> None: ...
    @property
    def xyz(self) -> Sequence[float]: ...
    @xyz.setter
    def xyz(self, value: Sequence[float]) -> None: ...
