"""
Hand-written stub. `kivy.graphics.instructions` is a compiled Cython module, so
pyright's stub generator had no source to read. Signatures follow the kivy 2.3.1
sources in `.claude/kivy`.

`texture` and `shader` values are `Any` because `kivy.graphics.texture` and
`kivy.graphics.shader` are themselves unstubbed compiled modules.
"""

from collections.abc import Callable, Sequence
from typing import Any

from kivy.event import ObjectWithUid

__all__ = (
    "Instruction",
    "InstructionGroup",
    "ContextInstruction",
    "VertexInstruction",
    "Canvas",
    "CanvasBase",
    "RenderContext",
    "Callback",
)

class Instruction(ObjectWithUid):
    group: str | None
    def __init__(self, **kwargs: Any) -> None: ...
    @property
    def needs_redraw(self) -> bool: ...
    @property
    def proxy_ref(self) -> Instruction: ...
    def flag_update(self, do_parent: int = 1) -> None: ...
    def flag_data_update(self) -> None: ...

class InstructionGroup(Instruction):
    children: list[Instruction]
    def add(self, c: Instruction) -> None: ...
    def insert(self, index: int, c: Instruction) -> None: ...
    def remove(self, c: Instruction) -> None: ...
    def indexof(self, c: Instruction) -> int: ...
    def length(self) -> int: ...
    def clear(self) -> None: ...
    def remove_group(self, groupname: str) -> None: ...
    def get_group(self, groupname: str) -> list[Instruction]: ...

class ContextInstruction(Instruction): ...

class VertexInstruction(Instruction):
    @property
    def texture(self) -> Any: ...
    @texture.setter
    def texture(self, value: Any) -> None: ...
    @property
    def source(self) -> str | None: ...
    @source.setter
    def source(self, value: str | None) -> None: ...
    @property
    def tex_coords(self) -> Sequence[float]: ...
    @tex_coords.setter
    def tex_coords(self, value: Sequence[float]) -> None: ...

class Callback(Instruction):
    def __init__(
        self, callback: Callable[[Instruction], object] | None = None, **kwargs: Any
    ) -> None: ...
    def ask_update(self) -> None: ...
    @property
    def callback(self) -> Callable[[Instruction], object] | None: ...
    @callback.setter
    def callback(self, func: Callable[[Instruction], object] | None) -> None: ...
    @property
    def reset_context(self) -> int: ...
    @reset_context.setter
    def reset_context(self, value: bool | int) -> None: ...

class CanvasBase(InstructionGroup):
    def __enter__(self) -> None: ...
    def __exit__(self, *largs: object) -> None: ...

class Canvas(CanvasBase):
    def ask_update(self) -> None: ...
    def draw(self) -> None: ...
    @property
    def before(self) -> CanvasBase: ...
    @property
    def after(self) -> CanvasBase: ...
    @property
    def has_before(self) -> bool: ...
    @property
    def has_after(self) -> bool: ...
    @property
    def opacity(self) -> float: ...
    @opacity.setter
    def opacity(self, value: float) -> None: ...

class RenderContext(Canvas):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getitem__(self, key: str) -> Any: ...
    def __setitem__(self, key: str, val: Any) -> None: ...
    @property
    def shader(self) -> Any: ...
    @property
    def use_parent_projection(self) -> int: ...
    @use_parent_projection.setter
    def use_parent_projection(self, value: bool | int) -> None: ...
    @property
    def use_parent_modelview(self) -> int: ...
    @use_parent_modelview.setter
    def use_parent_modelview(self, value: bool | int) -> None: ...
    @property
    def use_parent_frag_modelview(self) -> int: ...
    @use_parent_frag_modelview.setter
    def use_parent_frag_modelview(self, value: bool | int) -> None: ...
