#:import DebugBoxLayout mindref.lib.widgets.behavior.DebugBoxLayout
#:import DebugFloatLayout mindref.lib.widgets.behavior.DebugFloatLayout
#:import ThemedLabelButton mindref.lib.widgets.buttons.buttons.ThemedLabelButton
#:import ContainedLabelButton mindref.lib.widgets.buttons.buttons.ContainedLabelButton
#:import LabelButton mindref.lib.widgets.buttons.buttons.LabelButton
#:import HSeparator mindref.lib.widgets.separator.HSeparator

 
<EditScreen>:
    app: app
    canvas.before:
        Color:
            rgba: app.colors['Dark']
        Rectangle:
            size: self.size
            pos: self.pos
    DebugBoxLayout:
        id: layout
        debug_layout: False
        orientation: 'vertical'
        DebugFloatLayout:
            id: title_bar
            debug_layout: False
            size_hint_x: 1
            size_hint_y: .07
            pos_hint: {"top": 1}
            canvas:
                Color:
                    rgba: app.colors['RichBlack']
                Rectangle:
                    size: self.size
                    pos: self.pos
            DebugBoxLayout:
                height: self.minimum_height
                size_hint_y: None
                pos_hint: {"center_x": 0.5, "center_y": 0.5}
                Label:
                    id: title_label
                    text: root.editing_note.label if root.editing_note else ""
                    text_size: root.width, None
                    size: self.texture_size
                    font_size: app.base_font_size + dp(4)
                    halign: 'center'
                    valign: 'center'
        HSeparator:
            color: [*app.colors['Gray-800'][:3], .2]
            height: dp(1)        
        CodeInput:
            id: code_input
            pos_hint: {"top": 1}
            size_hint_x: 1
            size_hint_y: .9
            lexer: root.lexer
            style_name: 'github-dark'
            font_family: app.fonts['mono']
            font_size: app.base_font_size
        DebugFloatLayout:
            debug_layout: False
            id: bottom_bar
            size_hint_x: 1
            size_hint_y: .1
            pos_hint: {"bottom": 1}
            canvas:
                Color:
                    rgba: app.colors['RichBlack']
                Rectangle:
                    size: self.size
                    pos: self.pos
            DebugBoxLayout:
                id: button_bar
                debug_layout: False
                orientation: 'horizontal'
                size_hint_y: 1
                size_hint_x: None
                width: self.minimum_width
                pos_hint: {"right": 1, "y": 0}
                padding: [dp(8), dp(8), dp(8), dp(8)]
                spacing: dp(8)
                LabelButton:
                    size_hint: (None, None)
                    pos_hint: {"center_y": 0.5}
                    color: app.colors['Warn']
                    text: "Cancel"
                    on_release: app.cancel_edit_note()
                LabelButton:
                    size_hint: (None, None)
                    pos_hint: {"center_y": 0.5}
                    text: "Save"
                    on_release: root.app.save_editing_note()
            