#:import Toolbar widgets.toolbar


<NoteCategories>:
    category_container: category_container
    orientation: 'vertical'
    Toolbar:
        size_hint_y: None
        padding: dp(20), dp(10), dp(10), dp(5)
        height: dp(50)

    GridLayout:
        size_hint_y: None
        height: self.minimum_height
        id: category_container
        cols: 4
        padding: dp(10)
        spacing: dp(5)
