<BaseLabel@Label>:
    font_size: app.base_font_size
    font_family: app.fonts['default']

<SmallLabel@BaseLabel>:
    font_size: app.base_font_size - sp(2)

<LargeLabel@BaseLabel>:
    font_size: app.base_font_size + sp(2)

<XLargeLabel@BaseLabel>:
    font_size: app.base_font_size + sp(3)

<ExpandingLabel@BaseLabel>:
    font_size: self.height / 2

<TitleInput>:
    font_size: app.base_font_size
    font_family: app.fonts['default']
    multiline: False
