"""Hand-written stub for `kivy.effects.kinetic` (kivy 2.3.1)."""

from kivy.event import EventDispatcher
from kivy.properties import BooleanProperty, NumericProperty

__all__ = ("KineticEffect",)

class KineticEffect(EventDispatcher):
    velocity: NumericProperty
    friction: NumericProperty
    value: NumericProperty
    is_manual: BooleanProperty
    max_history: NumericProperty
    min_distance: NumericProperty
    min_velocity: NumericProperty
    std_dt: NumericProperty
    def __init__(self, **kwargs: object) -> None: ...
    def apply_distance(self, distance: float) -> None: ...
    def start(self, val: float, t: float | None = None) -> None: ...
    def update(self, val: float, t: float | None = None) -> None: ...
    def stop(self, val: float, t: float | None = None) -> None: ...
    def cancel(self) -> None: ...
    def update_velocity(self, dt: float) -> None: ...
