from collections.abc import Sequence
from typing import Protocol

Cell = tuple[int, int]

class WidthMeasurer(Protocol):
    def width(self, text: str) -> float: ...

class ConcaveFillet:
    corner: tuple[float, float]
    center: tuple[float, float]
    def __init__(
        self, corner: tuple[float, float], center: tuple[float, float]
    ) -> None: ...

def expand_tabs(line: str, tab_width: int) -> str: ...
def prefix_width(
    measurer: WidthMeasurer, line: str, col: int, tab_width: int
) -> float: ...
def column_at(measurer: WidthMeasurer, line: str, tab_width: int, x: float) -> int: ...
def row_at(y_from_top: float, line_height: float, row_count: int) -> int: ...
def word_range(line: str, col: int) -> tuple[int, int]: ...
def order_cells(a: Cell, b: Cell) -> tuple[Cell, Cell]: ...
def row_spans(
    lines: Sequence[str], start: Cell, end: Cell
) -> list[tuple[int, int, int]]: ...
def joint_radius(own: float, neighbor: float, radius: float) -> float: ...
def edge_protrudes(own: float, neighbor: float, side: float) -> bool: ...
def neighbor_reaches(
    own: float, neighbor: tuple[float, float], side: float
) -> bool: ...
def corner_radii(
    edges: Sequence[tuple[float, float]], index: int, radius: float
) -> list[float]: ...
def corner_fillets(
    edges: Sequence[tuple[float, float]],
    index: int,
    radius: float,
    y_top: float,
    y_bottom: float,
) -> list[ConcaveFillet]: ...
def fillet_fan(
    fillet: ConcaveFillet, segments: int = 6
) -> list[tuple[float, float]]: ...
def text_of_range(lines: Sequence[str], start: Cell, end: Cell) -> str: ...
def widest_width(
    measurer: WidthMeasurer, lines: Sequence[str], tab_width: int
) -> float: ...
