<DrawerLayout>:
    background_color: app.colors['Primary']
    overlay_alpha: 0.3
    canvas:
        Color:
            rgba: [0,0,0,self._anim_alpha]
        Rectangle:
            size: self._window_size
            pos: 0,0
        Color:
            rgba: self.background_color
        BorderImage:
            source: app.atlas_service.uri_for("bg_normal", atlas_name="textures")
            border: [dp(16), dp(16), dp(16), dp(16)]
            pos: self.pos
            size: self.size

