"""
This type stub file was generated by pyright.
"""

from kivy.uix.label import Label
from kivy.uix.behaviors import ButtonBehavior

__all__ = ("Button",)

class Button(ButtonBehavior, Label):
    """Button class, see module documentation for more information.

    .. versionchanged:: 1.8.0
        The behavior / logic of the button has been moved to
        :class:`~kivy.uix.behaviors.ButtonBehaviors`.

    """

    background_color = ...
    background_normal = ...
    background_down = ...
    background_disabled_normal = ...
    background_disabled_down = ...
    border = ...
