"""
This type stub file was generated by pyright.
"""

from kivy.uix.widget import Widget
from kivy.uix.layout import Layout

__all__ = ("FloatLayout",)

class FloatLayout(Layout):
    """Float layout class. See module documentation for more information."""
    def __init__(self, **kwargs) -> None: ...
    def do_layout(self, *largs, **kwargs): ...
    def add_widget(self, widget: Widget, *args: object, **kwargs: object) -> None: ...
    def remove_widget(
        self, widget: Widget, *args: object, **kwargs: object
    ) -> None: ...
