"""
This type stub file was generated by pyright.
"""

from kivy.uix.anchorlayout import AnchorLayout

__all__ = ("ModalView",)

class ModalView(AnchorLayout):
    """ModalView class. See module documentation for more information.

    :Events:
        `on_pre_open`:
            Fired before the ModalView is opened. When this event is fired
            ModalView is not yet added to window.
        `on_open`:
            Fired when the ModalView is opened.
        `on_pre_dismiss`:
            Fired before the ModalView is closed.
        `on_dismiss`:
            Fired when the ModalView is closed. If the callback returns True,
            the dismiss will be canceled.

    .. versionchanged:: 1.11.0
        Added events `on_pre_open` and `on_pre_dismiss`.

    .. versionchanged:: 2.0.0
        Added property 'overlay_color'.

    .. versionchanged:: 2.1.0
        Marked `attach_to` property as deprecated.

    """

    auto_dismiss = ...
    attach_to = ...
    background_color = ...
    background = ...
    border = ...
    overlay_color = ...
    _anim_alpha = ...
    _anim_duration = ...
    _window = ...
    _is_open = ...
    _touch_started_inside = ...
    __events__ = ...
    def __init__(self, **kwargs) -> None: ...
    def open(self, *_args, **kwargs) -> None:
        """Display the modal in the Window.

        When the view is opened, it will be faded in with an animation. If you
        don't want the animation, use::

            view.open(animation=False)

        """
        ...

    def dismiss(self, *_args, **kwargs) -> None:
        """Close the view if it is open.

        If you really want to close the view, whatever the on_dismiss
        event returns, you can use the *force* keyword argument::

            view = ModalView()
            view.dismiss(force=True)

        When the view is dismissed, it will be faded out before being
        removed from the parent. If you don't want this animation, use::

            view.dismiss(animation=False)

        """
        ...

    def on_motion(self, etype, me) -> Literal[True]: ...
    def on_touch_down(self, touch) -> Literal[True]:
        """touch down event handler."""
        ...

    def on_touch_move(self, touch) -> Literal[True]:
        """touch moved event handler."""
        ...

    def on_touch_up(self, touch) -> Literal[True]:
        """touch up event handler."""
        ...

    def on__anim_alpha(self, _instance, value) -> None:
        """animation progress callback."""
        ...

    def on_pre_open(self) -> None:
        """default pre-open event handler."""
        ...

    def on_open(self) -> None:
        """default open event handler."""
        ...

    def on_pre_dismiss(self) -> None:
        """default pre-dismiss event handler."""
        ...

    def on_dismiss(self) -> None:
        """default dismiss event handler."""
        ...

if __name__ == "__main__":
    content = ...
    view = ...
    layout = ...
