"""
This type stub file was generated by pyright.
"""

from kivy.uix.widget import Widget

__all__ = ("StencilView",)

class StencilView(Widget):
    """StencilView class. See module documentation for more information."""

    ...
