"""
This type stub file was generated by pyright.
"""

from kivy.uix.button import Button
from kivy.uix.behaviors import ToggleButtonBehavior

__all__ = ("ToggleButton",)

class ToggleButton(ToggleButtonBehavior, Button):
    """Toggle button class, see module documentation for more information."""

    ...
