"""
This type stub file was generated by pyright.
"""

from collections.abc import Generator
from typing import Literal

from kivy.event import EventDispatcher
from kivy.input.motionevent import MotionEvent

__all__ = ("Widget", "WidgetException")
_widget_destructors = ...

class WidgetException(Exception):
    """Fired when the widget gets an exception."""

    ...

class WidgetMetaclass(type):
    """Metaclass to automatically register new widgets for the
    :class:`~kivy.factory.Factory`.

    .. warning::
        This metaclass is used by the Widget. Do not use it directly!
    """
    def __init__(mcs, name, bases, attrs) -> None: ...

class WidgetBase(EventDispatcher, metaclass=WidgetMetaclass): ...

class Widget(WidgetBase):
    """Widget class. See module documentation for more information.

    :Events:
        `on_touch_down`: `(touch, )`
            Fired when a new touch event occurs. `touch` is the touch object.
        `on_touch_move`: `(touch, )`
            Fired when an existing touch moves. `touch` is the touch object.
        `on_touch_up`: `(touch, )`
            Fired when an existing touch disappears. `touch` is the touch
            object.
        `on_kv_post`: `(base_widget, )`
            Fired after all the kv rules associated with the widget
            and all other widgets that are in any of those rules have had
            all their kv rules applied. `base_widget` is the base-most widget
            whose instantiation triggered the kv rules (i.e. the widget
            instantiated from Python, e.g. ``MyWidget()``).

            .. versionchanged:: 1.11.0

    .. warning::
        Adding a `__del__` method to a class derived from Widget with Python
        prior to 3.4 will disable automatic garbage collection for instances
        of that class. This is because the Widget class creates reference
        cycles, thereby `preventing garbage collection
        <https://docs.python.org/2/library/gc.html#gc.garbage>`_.

    .. versionchanged:: 1.0.9
        Everything related to event properties has been moved to the
        :class:`~kivy.event.EventDispatcher`. Event properties can now be used
        when constructing a simple class without subclassing :class:`Widget`.

    .. versionchanged:: 1.5.0
        The constructor now accepts on_* arguments to automatically bind
        callbacks to properties or events, as in the Kv language.
    """

    __metaclass__ = WidgetMetaclass
    __events__ = ...
    _proxy_ref = ...
    def __init__(self, **kwargs) -> None: ...
    @property
    def proxy_ref(self):
        """Return a proxy reference to the widget, i.e. without creating a
        reference to the widget. See `weakref.proxy
        <http://docs.python.org/2/library/weakref.html?highlight\
        =proxy#weakref.proxy>`_ for more information.

        .. versionadded:: 1.7.2
        """
        ...

    def __hash__(self) -> int: ...
    def apply_class_lang_rules(
        self, root=..., ignored_consts=..., rule_children=...
    ) -> None:
        """
        Method that is called by kivy to apply the kv rules of this widget's
        class.

        :Parameters:
            `root`: :class:`Widget`
                The root widget that instantiated this widget in kv, if the
                widget was instantiated in kv, otherwise ``None``.
            `ignored_consts`: set
                (internal) See :meth:`~kivy.lang.builder.BuilderBase.apply`.
            `rule_children`: list
                (internal) See :meth:`~kivy.lang.builder.BuilderBase.apply`.

        This is useful to be able to execute code before/after the class kv
        rules are applied to the widget. E.g. if the kv code requires some
        properties to be initialized before it is used in a binding rule.
        If overwriting remember to call ``super``, otherwise the kv rules will
        not be applied.

        In the following example,

        .. code-block:: python

            class MyWidget(Widget):
                pass

            class OtherWidget(MyWidget):
                pass

        .. code-block:: kv

        <MyWidget>:
            my_prop: some_value

        <OtherWidget>:
            other_prop: some_value

        When ``OtherWidget`` is instantiated with ``OtherWidget()``, the
        widget's :meth:`apply_class_lang_rules` is called and it applies the
        kv rules of this class - ``<MyWidget>`` and ``<OtherWidget>``.

        Similarly, when the widget is instantiated from kv, e.g.

        .. code-block:: kv

            <MyBox@BoxLayout>:
                height: 55
                OtherWidget:
                    width: 124

        ``OtherWidget``'s :meth:`apply_class_lang_rules` is called and it
        applies the kv rules of this class - ``<MyWidget>`` and
        ``<OtherWidget>``.

        .. note::

            It applies only the class rules not the instance rules. I.e. in the
            above kv example in the ``MyBox`` rule when ``OtherWidget`` is
            instantiated, its :meth:`apply_class_lang_rules` applies the
            ``<MyWidget>`` and ``<OtherWidget>`` rules to it - it does not
            apply the ``width: 124`` rule. The ``width: 124`` rule is part of
            the ``MyBox`` rule and is applied by the ``MyBox``'s instance's
            :meth:`apply_class_lang_rules`.

        .. versionchanged:: 1.11.0
        """
        ...

    def collide_point(self, x: float, y: float) -> bool: ...
    def collide_widget(self, wid) -> bool:
        """
        Check if another widget collides with this widget. This function
        performs an axis-aligned bounding box intersection test by default.

        :Parameters:
            `wid`: :class:`Widget` class
                Widget to test collision with.

        :Returns:
            bool. True if the other widget collides with this widget, False
            otherwise.

        .. code-block:: python

            >>> wid = Widget(size=(50, 50))
            >>> wid2 = Widget(size=(50, 50), pos=(25, 25))
            >>> wid.collide_widget(wid2)
            True
            >>> wid2.pos = (55, 55)
            >>> wid.collide_widget(wid2)
            False
        """
        ...

    def on_motion(self, etype, me) -> bool | None:
        """Called when a motion event is received.

        :Parameters:
            `etype`: `str`
                Event type, one of "begin", "update" or "end"
            `me`: :class:`~kivy.input.motionevent.MotionEvent`
                Received motion event
        :Returns: `bool`
            `True` to stop event dispatching

        .. versionadded:: 2.1.0

        .. warning::
            This is an experimental method and it remains so while this warning
            is present.
        """
        ...

    def on_touch_down(self, touch: MotionEvent) -> bool | None: ...
    def on_touch_move(self, touch: MotionEvent) -> bool | None: ...
    def on_touch_up(self, touch: MotionEvent) -> bool | None: ...
    def on_kv_post(self, base_widget) -> None: ...
    def add_widget(
        self,
        widget: Widget,
        index: int = 0,
        canvas: Literal["before", "after"] | None = None,
    ) -> None: ...
    def remove_widget(self, widget: Widget) -> None: ...
    def clear_widgets(self, children=...) -> None:
        """
        Remove all (or the specified) :attr:`~Widget.children` of this widget.
        If the 'children' argument is specified, it should be a list (or
        filtered list) of children of the current widget.

        .. versionchanged:: 1.8.0
            The `children` argument can be used to specify the children you
            want to remove.
        .. versionchanged:: 2.1.0

            Specifying an empty ``children`` list leaves the widgets unchanged.
            Previously it was treated like ``None`` and all children were
            removed.
        """
        ...

    def register_for_motion_event(self, type_id, widget=...) -> None:
        """Register to receive motion events of `type_id`.

        Override :meth:`on_motion` or bind to `on_motion` event to handle
        the incoming motion events.

        :Parameters:
            `type_id`: `str`
                Motion event type id (eg. "touch", "hover", etc.)
            `widget`: `Widget`
                Child widget or `self` if omitted

        .. versionadded:: 2.1.0

        .. note::
            Method can be called multiple times with the same arguments.

        .. warning::
            This is an experimental method and it remains so while this warning
            is present.
        """
        ...

    def unregister_for_motion_event(self, type_id, widget=...) -> None:
        """Unregister to receive motion events of `type_id`.

        :Parameters:
            `type_id`: `str`
                Motion event type id (eg. "touch", "hover", etc.)
            `widget`: `Widget`
                Child widget or `self` if omitted

        .. versionadded:: 2.1.0

        .. note::
            Method can be called multiple times with the same arguments.

        .. warning::
            This is an experimental method and it remains so while this warning
            is present.
        """
        ...

    def export_to_png(self, filename, *args, **kwargs) -> None:
        """Saves an image of the widget and its children in png format at the
        specified filename. Works by removing the widget canvas from its
        parent, rendering to an :class:`~kivy.graphics.fbo.Fbo`, and calling
        :meth:`~kivy.graphics.texture.Texture.save`.

        .. note::

            The image includes only this widget and its children. If you want
            to include widgets elsewhere in the tree, you must call
            :meth:`~Widget.export_to_png` from their common parent, or use
            :meth:`~kivy.core.window.WindowBase.screenshot` to capture the
            whole window.

        .. note::

            The image will be saved in png format, you should include the
            extension in your filename.

        .. versionadded:: 1.9.0

        :Parameters:
            `filename`: str
                The filename with which to save the png.
            `scale`: float
                The amount by which to scale the saved image, defaults to 1.

                .. versionadded:: 1.11.0
        """
        ...

    def export_as_image(self, *args, **kwargs) -> Image:
        """Return an core :class:`~kivy.core.image.Image` of the actual
        widget.

        .. versionadded:: 1.11.0
        """
        ...

    def get_root_window(self) -> None:
        """Return the root window.

        :Returns:
            Instance of the root window. Can be a
            :class:`~kivy.core.window.WindowBase` or
            :class:`Widget`.
        """
        ...

    def get_parent_window(self) -> None:
        """Return the parent window.

        :Returns:
            Instance of the parent window. Can be a
            :class:`~kivy.core.window.WindowBase` or
            :class:`Widget`.
        """
        ...

    def walk(self, restrict=..., loopback=...) -> Generator[Self | Any, Any, None]:
        """Iterator that walks the widget tree starting with this widget and
        goes forward returning widgets in the order in which layouts display
        them.

        :Parameters:
            `restrict`: bool, defaults to False
                If True, it will only iterate through the widget and its
                children (or children of its children etc.). Defaults to False.
            `loopback`: bool, defaults to False
                If True, when the last widget in the tree is reached,
                it'll loop back to the uppermost root and start walking until
                we hit this widget again. Naturally, it can only loop back when
                `restrict` is False. Defaults to False.

        :return:
            A generator that walks the tree, returning widgets in the
            forward layout order.

        For example, given a tree with the following structure:

        .. code-block:: kv

            GridLayout:
                Button
                BoxLayout:
                    id: box
                    Widget
                    Button
                Widget

        walking this tree:

        .. code-block:: python

            >>> # Call walk on box with loopback True, and restrict False
            >>> [type(widget) for widget in box.walk(loopback=True)]
            [<class 'BoxLayout'>, <class 'Widget'>, <class 'Button'>,
                <class 'Widget'>, <class 'GridLayout'>, <class 'Button'>]
            >>> # Now with loopback False, and restrict False
            >>> [type(widget) for widget in box.walk()]
            [<class 'BoxLayout'>, <class 'Widget'>, <class 'Button'>,
                <class 'Widget'>]
            >>> # Now with restrict True
            >>> [type(widget) for widget in box.walk(restrict=True)]
            [<class 'BoxLayout'>, <class 'Widget'>, <class 'Button'>]

        .. versionadded:: 1.9.0
        """
        ...

    def walk_reverse(self, loopback: bool = False) -> Generator[Widget, None, None]: ...
    def to_widget(
        self, x: float, y: float, relative: bool = ...
    ) -> tuple[float, float]:
        """Convert the coordinate from window to local (current widget)
        coordinates.

        See :mod:`~kivy.uix.relativelayout` for details on the coordinate
        systems.
        """
        ...

    def to_window(
        self, x: float, y: float, initial: bool = ..., relative: bool = ...
    ) -> tuple[float, float]:
        """If ``initial`` is True, the default, it transforms **parent**
        coordinates to window coordinates. Otherwise, it transforms **local**
        (current widget) coordinates to window coordinates.

        See :mod:`~kivy.uix.relativelayout` for details on the coordinate
        systems.
        """
        ...

    def to_parent(
        self, x: float, y: float, *, relative: bool = ...
    ) -> tuple[float, float]: ...
    def to_local(
        self, x: float, y: float, *, relative: bool = ...
    ) -> tuple[float, float]: ...
    def get_window_matrix(self, x=..., y=...):
        """Calculate the transformation matrix to convert between window and
        widget coordinates.

        :Parameters:
            `x`: float, defaults to 0
                Translates the matrix on the x axis.
            `y`: float, defaults to 0
                Translates the matrix on the y axis.
        """
        ...

    x = ...
    y = ...
    width = ...
    height = ...
    pos = ...
    size = ...
    def get_right(self): ...
    def set_right(self, value) -> None: ...

    right = ...
    def get_top(self): ...
    def set_top(self, value) -> None: ...

    top = ...
    def get_center_x(self): ...
    def set_center_x(self, value) -> None: ...

    center_x = ...
    def get_center_y(self): ...
    def set_center_y(self, value) -> None: ...

    center_y = ...
    center = ...
    cls = ...
    children = ...
    parent = ...
    size_hint_x = ...
    size_hint_y = ...
    size_hint = ...
    pos_hint = ...
    size_hint_min_x = ...
    size_hint_min_y = ...
    size_hint_min = ...
    size_hint_max_x = ...
    size_hint_max_y = ...
    size_hint_max = ...
    ids = ...
    opacity = ...
    def on_opacity(self, instance, value) -> None: ...

    canvas = ...
    def get_disabled(self) -> bool: ...
    def set_disabled(self, value) -> Literal[True] | None: ...
    def inc_disabled(self, count=...) -> None: ...
    def dec_disabled(self, count=...) -> None: ...

    disabled = ...
    motion_filter = ...
