"""
This type stub file was generated by pyright.
"""

from collections.abc import Callable, Iterable

from .markdown import Markdown
from .block_parser import BlockParser
from .inline_parser import InlineParser
from .renderers import AstRenderer, BaseRenderer, HTMLRenderer
from .plugins import PLUGINS
from .util import escape, escape_html, escape_url, unikey

def create_markdown[TDocument](
    escape: bool = ...,
    hard_wrap: bool = ...,
    *,
    renderer: BaseRenderer[TDocument],
    plugins: Iterable[str | Callable[[Markdown[TDocument]], None]] = ...,
) -> Markdown[TDocument]: ...

html = ...

def markdown(text, escape=..., renderer=..., plugins=...): ...

__all__ = [
    "Markdown",
    "AstRenderer",
    "HTMLRenderer",
    "BlockParser",
    "InlineParser",
    "escape",
    "escape_url",
    "escape_html",
    "unikey",
    "html",
    "create_markdown",
    "markdown",
]
__version__ = ...
