"""
This type stub file was generated by pyright.
"""

from kivy.core.text import Label

__all__ = ("MarkupLabel",)
MarkupLabelBase = ...
if Label is None:
    MarkupLabelBase = ...

class MarkupLabel(MarkupLabelBase):
    """Markup text label.

    See module documentation for more information.
    """
    def __init__(self, *largs, **kwargs) -> None: ...
    @property
    def refs(self) -> dict[Any, Any]:
        """Get the bounding box of all the ``[ref=...]``::

        { 'refA': ((x1, y1, x2, y2), (x1, y1, x2, y2)), ... }
        """
        ...

    @property
    def anchors(self) -> dict[Any, Any]:
        """Get the position of all the ``[anchor=...]``::

        { 'anchorA': (x, y), 'anchorB': (x, y), ... }
        """
        ...

    @property
    def markup(self) -> list[str | Any]:
        """Return the text with all the markup split::

        >>> MarkupLabel('[b]Hello world[/b]').markup
        >>> ('[b]', 'Hello world', '[/b]')

        """
        ...

    def render(self, real=...) -> tuple[int, int]: ...
    def render_lines(self, lines, options, render_text, y, size): ...
    def shorten_post(self, lines, w, h, margin=...):
        """Shortens the text to a single line according to the label options.

        This function operates on a text that has already been laid out because
        for markup, parts of text can have different size and options.

        If :attr:`text_size` [0] is None, the lines are returned unchanged.
        Otherwise, the lines are converted to a single line fitting within the
        constrained width, :attr:`text_size` [0].

        :params:

            `lines`: list of `LayoutLine` instances describing the text.
            `w`: int, the width of the text in lines, including padding.
            `h`: int, the height of the text in lines, including padding.
            `margin` int, the additional space left on the sides. This is in
            addition to :attr:`padding_x`.

        :returns:
            3-tuple of (xw, h, lines), where w, and h is similar to the input
            and contains the resulting width / height of the text, including
            padding. lines, is a list containing a single `LayoutLine`, which
            contains the words for the line.
        """
        ...
