"""
This type stub file was generated by pyright.
"""

from pygments.lexer import RegexLexer

"""Pygments lexer for kv language
"""

class KivyLexer(RegexLexer):
    name = ...
    aliases = ...
    filenames = ...
    tokens = ...

if __name__ == "__main__":
    k = ...
