<NoteCategoryChooser>:
    cols: 4
    padding: 10
    spacing: 10

<NoteCategoryButton>:
    orientation: 'vertical'
    padding: 10
    image: image
    canvas.before:
        RoundedRectangle:
            pos: self.pos
            size: self.size
            texture: self.tx_bg_normal if self.state == 'normal' else self.tx_bg_down
    Image:
        id: image
        source: root.source
        mipmap: True

    Label:
        text: root.text
        size_hint_x: 1
        size_hint_y: 0.4
