<BaseLabel@Label>:
    font_size: app.base_font_size
    font_family: app.fonts['default']

<SmallLabel@BaseLabel>:
    font_size: app.base_font_size - sp(2)
    font_family: app.fonts['default']

<LargeLabel@BaseLabel>:
    font_size: app.base_font_size + sp(2)
    font_family: app.fonts['default']

<TitleInput>:
    font_size: app.base_font_size
    font_family: app.fonts['default']
    multiline: False
