<RefreshSymbol>:
    size_hint_y: None
    size_hint_x: None
    width: dp(80)
    height: dp(80)
    pos_hint: {"center_x": 0.5, "center_y": 0.9}

    canvas.before:
        PushMatrix
        Rotate:
            angle: self.rotation
            origin: self.center
    canvas:
        Color:
            rgb: app.colors['White']
        Rectangle:
            size: root.size
            pos: self.pos
            source: self.source
    canvas.after:
        PopMatrix
