"""
This type stub file was generated by pyright.
"""

from kivy.input.motionevent import MotionEvent

__all__ = ("ButtonBehavior",)

class ButtonBehavior:
    """
    This `mixin <https://en.wikipedia.org/wiki/Mixin>`_ class provides
    :class:`~kivy.uix.button.Button` behavior. Please see the
    :mod:`button behaviors module <kivy.uix.behaviors.button>` documentation
    for more information.

    :Events:
        `on_press`
            Fired when the button is pressed.
        `on_release`
            Fired when the button is released (i.e. the touch/click that
            pressed the button goes away).

    """

    state = ...
    last_touch = ...
    min_state_time = ...
    always_release = ...
    def __init__(self, **kwargs) -> None: ...
    def cancel_event(self, *args) -> None: ...
    def on_touch_down(self, touch: MotionEvent) -> bool: ...
    def on_touch_move(self, touch: MotionEvent) -> bool | None: ...
    def on_touch_up(self, touch: MotionEvent) -> bool | None: ...
    def on_press(self) -> None: ...
    def on_release(self) -> None: ...
    def trigger_action(self, duration=...) -> None:
        """Trigger whatever action(s) have been bound to the button by calling
        both the on_press and on_release callbacks.

        This is similar to a quick button press without using any touch events,
        but note that like most kivy code, this is not guaranteed to be safe to
        call from external threads. If needed use
        :class:`Clock <kivy.clock.Clock>` to safely schedule this function and
        the resulting callbacks to be called from the main thread.

        Duration is the length of the press in seconds. Pass 0 if you want
        the action to happen instantly.

        .. versionadded:: 1.8.0
        """
        ...
