"""
This type stub file was generated by pyright.
"""

from kivy.event import EventDispatcher

__all__ = ("CodeNavigationBehavior",)

class CodeNavigationBehavior(EventDispatcher):
    """Code navigation behavior. Modifies the navigation behavior in TextInput
    to work like an IDE instead of a word processor. Please see the
    :mod:`code navigation behaviors module <kivy.uix.behaviors.codenavigation>`
    documentation for more information.

    .. versionadded:: 1.9.1
    """

    ...
