"""
This type stub file was generated by pyright.
"""

__all__ = ("CoverBehavior",)

class CoverBehavior:
    """The CoverBehavior `mixin <https://en.wikipedia.org/wiki/Mixin>`_
    provides rendering a texture covering full widget size keeping aspect ratio
    of the original texture.

    .. versionadded:: 1.10.0
    """

    reference_size = ...
    cover_size = ...
    cover_pos = ...
    def __init__(self, **kwargs) -> None: ...
    def calculate_cover(self, *args) -> None: ...
