"""
This type stub file was generated by pyright.
"""

__all__ = ("EmacsBehavior",)

class EmacsBehavior:
    """
    A `mixin <https://en.wikipedia.org/wiki/Mixin>`_ that enables Emacs-style
    keyboard shortcuts for the :class:`~kivy.uix.textinput.TextInput` widget.
    Please see the :mod:`Emacs behaviors module <kivy.uix.behaviors.emacs>`
    documentation for more information.

    .. versionadded:: 1.9.1
    """

    key_bindings = ...
    def __init__(self, **kwargs) -> None: ...
    def keyboard_on_key_down(self, window, keycode, text, modifiers) -> None: ...
    def delete_word_right(self) -> None:
        """Delete text right of the cursor to the end of the word"""
        ...

    def delete_word_left(self) -> None:
        """Delete text left of the cursor to the beginning of word"""
        ...
