"""
This type stub file was generated by pyright.
"""

from kivy.config import Config

__all__ = ("FocusBehavior",)
_is_desktop = ...
_keyboard_mode = ...
if Config:
    _is_desktop = ...
    _keyboard_mode = ...

class FocusBehavior:
    """Provides keyboard focus behavior. When combined with other
    FocusBehavior widgets it allows one to cycle focus among them by pressing
    tab. Please see the
    :mod:`focus behavior module documentation <kivy.uix.behaviors.focus>`
    for more information.

    .. versionadded:: 1.9.0

    """

    _requested_keyboard = ...
    _keyboard = ...
    _keyboards = ...
    ignored_touch = ...
    keyboard = ...
    is_focusable = ...
    focus = ...
    focused = ...
    keyboard_suggestions = ...
    focus_next = ...
    focus_previous = ...
    keyboard_mode = ...
    input_type = ...
    unfocus_on_touch = ...
    def __init__(self, **kwargs) -> None: ...
    def keyboard_on_textinput(self, window, text) -> None: ...
    def on_touch_down(self, touch) -> None: ...
    def get_focus_next(self) -> Any | FocusBehavior | Self | None:
        """Returns the next focusable widget using either :attr:`focus_next`
        or the :attr:`children` similar to the order when tabbing forwards
        with the ``tab`` key.
        """
        ...

    def get_focus_previous(self) -> Any | FocusBehavior | Self | None:
        """Returns the previous focusable widget using either
        :attr:`focus_previous` or the :attr:`children` similar to the
        order when the ``tab`` + ``shift`` keys are triggered together.
        """
        ...

    def keyboard_on_key_down(self, window, keycode, text, modifiers) -> bool:
        """The method bound to the keyboard when the instance has focus.

        When the instance becomes focused, this method is bound to the
        keyboard and will be called for every input press. The parameters are
        the same as :meth:`kivy.core.window.WindowBase.on_key_down`.

        When overwriting the method in the derived widget, super should be
        called to enable tab cycling. If the derived widget wishes to use tab
        for its own purposes, it can call super after it has processed the
        character (if it does not wish to consume the tab).

        Similar to other keyboard functions, it should return True if the
        key was consumed.
        """
        ...

    def keyboard_on_key_up(self, window, keycode) -> bool:
        """The method bound to the keyboard when the instance has focus.

        When the instance becomes focused, this method is bound to the
        keyboard and will be called for every input release. The parameters are
        the same as :meth:`kivy.core.window.WindowBase.on_key_up`.

        When overwriting the method in the derived widget, super should be
        called to enable de-focusing on escape. If the derived widget wishes
        to use escape for its own purposes, it can call super after it has
        processed the character (if it does not wish to consume the escape).

        See :meth:`keyboard_on_key_down`
        """
        ...

    def show_keyboard(self) -> None:
        """
        Convenience function to show the keyboard in managed mode.
        """
        ...

    def hide_keyboard(self) -> None:
        """
        Convenience function to hide the keyboard in managed mode.
        """
        ...
