"""
This type stub file was generated by pyright.
"""

from kivy.uix.behaviors.button import ButtonBehavior

__all__ = ("ToggleButtonBehavior",)

class ToggleButtonBehavior(ButtonBehavior):
    """This `mixin <https://en.wikipedia.org/wiki/Mixin>`_ class provides
    :mod:`~kivy.uix.togglebutton` behavior. Please see the
    :mod:`togglebutton behaviors module <kivy.uix.behaviors.togglebutton>`
    documentation for more information.

    .. versionadded:: 1.8.0
    """

    __groups = ...
    group = ...
    allow_no_selection = ...
    def __init__(self, **kwargs) -> None: ...
    def on_group(self, *largs) -> None: ...
    @staticmethod
    def get_widgets(groupname) -> list[Any]:
        """Return a list of the widgets contained in a specific group. If the
        group doesn't exist, an empty list will be returned.

        .. note::

            Always release the result of this method! Holding a reference to
            any of these widgets can prevent them from being garbage collected.
            If in doubt, do::

                l = ToggleButtonBehavior.get_widgets('mygroup')
                # do your job
                del l

        .. warning::

            It's possible that some widgets that you have previously
            deleted are still in the list. The garbage collector might need
            to release other objects before flushing them.
        """
        ...
