<ContentRST>:
    id: parent
    rst_doc: doc
    RstDocument:
        id: doc
        size_hint: 0.99, 0.95
        anchor_x: "center"
        anchor_y: "center"
        text: parent.note_text
        colors: {'background': parent.bg_color, 'link': 'ce5c00ff', 'paragraph': parent.paragraph_color, 'title': 'F5BD17ff', 'bullet': '000000ff'}
        show_errors : True
        mipmap: True
        base_font_size: 30
