"""
This type stub file was generated by pyright.
"""

from typing import Any

from kivy.base import async_runTouchApp, runTouchApp, stopTouchApp
from kivy.config import ConfigParser
from kivy.core.window import WindowBase
from kivy.event import EventDispatcher
from kivy.properties import ObjectProperty, StringProperty
from kivy.uix.settings import Settings
from kivy.uix.widget import Widget

__all__ = ("App", "runTouchApp", "async_runTouchApp", "stopTouchApp")

class App(EventDispatcher):
    title: StringProperty
    icon: StringProperty
    use_kivy_settings: bool
    settings_cls: ObjectProperty
    kv_directory: StringProperty
    kv_file: StringProperty
    _running_app = ...
    __events__ = ...
    _user_data_dir = ...
    config: ConfigParser | None
    def __init__(self, **kwargs: Any) -> None: ...
    def build(self) -> Widget | None:
        """Initializes the application; it will be called only once.
        If this method returns a widget (tree), it will be used as the root
        widget and added to the window.

        :return:
            None or a root :class:`~kivy.uix.widget.Widget` instance
            if no self.root exists."""
        ...

    def build_config(self, config: ConfigParser) -> None: ...
    def build_settings(self, settings: Settings) -> None: ...
    def load_kv(self, filename: str | None = None) -> bool: ...
    def get_application_name(self) -> str: ...
    def get_application_icon(self) -> str | None:
        """Return the icon of the application."""
        ...

    def get_application_config(self, defaultpath: str = ...) -> str: ...
    @property
    def root_window(self) -> WindowBase | None: ...
    def load_config(self) -> ConfigParser | None:
        """(internal) This function is used for returning a ConfigParser with
        the application configuration. It's doing 3 things:

            #. Creating an instance of a ConfigParser
            #. Loading the default configuration by calling
               :meth:`build_config`, then
            #. If it exists, it loads the application configuration file,
               otherwise it creates one.

        :return:
            :class:`~kivy.config.ConfigParser` instance
        """
        ...

    @property
    def directory(self) -> str:
        """.. versionadded:: 1.0.7

        Return the directory where the application lives.
        """
        ...

    @property
    def user_data_dir(self) -> str:
        """
        .. versionadded:: 1.7.0

        Returns the path to the directory in the users file system which the
        application can use to store additional data.

        Different platforms have different conventions with regards to where
        the user can store data such as preferences, saved games and settings.
        This function implements these conventions. The <app_name> directory
        is created when the property is called, unless it already exists.

        On iOS, `~/Documents/<app_name>` is returned (which is inside the
        app's sandbox).

        On Windows, `%APPDATA%/<app_name>` is returned.

        On OS X, `~/Library/Application Support/<app_name>` is returned.

        On Linux, `$XDG_CONFIG_HOME/<app_name>` is returned.

        On Android, `Context.GetFilesDir
        <https://developer.android.com/reference/android/content/\
Context.html#getFilesDir()>`_ is returned.

        .. versionchanged:: 1.11.0

            On Android, this function previously returned
            `/sdcard/<app_name>`. This folder became read-only by default
            in Android API 26 and the user_data_dir has therefore been moved
            to a writeable location.

        """
        ...

    @property
    def name(self) -> str: ...
    def run(self) -> None:
        """Launches the app in standalone mode."""
        ...

    async def async_run(self, async_lib: str | None = None) -> None: ...
    def stop(self, *largs: Any) -> None: ...
    def pause(self, *largs: Any) -> None: ...
    def on_start(self) -> None:
        """Event handler for the `on_start` event which is fired after
        initialization (after build() has been called) but before the
        application has started running.
        """
        ...

    def on_stop(self) -> None:
        """Event handler for the `on_stop` event which is fired when the
        application has finished running (i.e. the window is about to be
        closed).
        """
        ...

    def on_pause(self) -> bool: ...
    def on_resume(self) -> None:
        """Event handler called when your application is resuming from
        the Pause mode.

        .. versionadded:: 1.1.0

        .. warning::

            When resuming, the OpenGL Context might have been damaged / freed.
            This is where you can reconstruct some of your OpenGL state
            e.g. FBO content.
        """
        ...

    @staticmethod
    def get_running_app() -> App | None: ...
    def on_config_change(
        self, config: ConfigParser, section: str, key: str, value: str
    ) -> None: ...
    def open_settings(self, *largs: Any) -> bool: ...
    def display_settings(self, settings: Settings) -> bool: ...
    def close_settings(self, *largs: Any) -> bool | None: ...
    def create_settings(self) -> Settings: ...
    def destroy_settings(self) -> None:
        """.. versionadded:: 1.8.0

        Dereferences the current settings panel if one
        exists. This means that when :meth:`App.open_settings` is next
        run, a new panel will be created and displayed. It doesn't
        affect any of the contents of the panel, but lets you (for
        instance) refresh the settings panel layout if you have
        changed the settings widget in response to a screen size
        change.

        If you have modified :meth:`~App.open_settings` or
        :meth:`~App.display_settings`, you should be careful to
        correctly detect if the previous settings widget has been
        destroyed.

        """
        ...

    def on_title(self, instance: App, title: str) -> None: ...
    def on_icon(self, instance: App, icon: str) -> None: ...
