"""
This type stub file was generated by pyright.
"""

import time
from sys import platform
from os import environ
from collections.abc import Callable
from typing import Protocol

from kivy._clock import (
    ClockEvent,
    ClockNotRunningError,
    CyClockBase,
    CyClockBaseFree,
    FreeClockEvent,
)

__all__ = (
    "Clock",
    "ClockNotRunningError",
    "ClockEvent",
    "FreeClockEvent",
    "CyClockBase",
    "CyClockBaseFree",
    "triggered",
    "ClockBaseBehavior",
    "ClockBaseInterruptBehavior",
    "ClockBaseInterruptFreeBehavior",
    "ClockBase",
    "ClockBaseInterrupt",
    "ClockBaseFreeInterruptAll",
    "ClockBaseFreeInterruptOnly",
    "mainthread",
)
if platform in ("win32", "cygwin"):
    _kernel32 = ...
else:
    _libc_usleep = ...

class ClockBaseBehavior:
    """The base of the kivy clock.

    :parameters:

        `async_lib`: string
            The async library to use when the clock is run asynchronously.
            Can be one of, `"asyncio"` when the standard library asyncio
            should be used, or `"trio"` if the trio library should be used.

            It defaults to `'asyncio'` or the value in the environmental
            variable `KIVY_EVENTLOOP` if set. :meth:`init_async_lib` can also
            be called directly to set the library.
    """

    _dt = ...
    _last_fps_tick = ...
    _start_tick = ...
    _fps = ...
    _rfps = ...
    _fps_counter = ...
    _rfps_counter = ...
    _frames = ...
    _frames_displayed = ...
    _events_duration = ...
    _duration_count = ...
    _sleep_time = ...
    _duration_ts0 = ...
    MIN_SLEEP = ...
    SLEEP_UNDERSHOOT = ...
    _async_lib = ...
    _async_wait_for = ...
    def __init__(self, async_lib=..., **kwargs) -> None: ...
    def init_async_lib(self, lib) -> None:
        """Manually sets the async library to use internally, when running in
        a asynchronous manner.

        This can be called anytime before the kivy event loop has started,
        but not once the kivy App is running.

        :parameters:

            `lib`: string
                The async library to use when the clock is run asynchronously.
                Can be one of, `"asyncio"` when the standard library asyncio
                should be used, or `"trio"` if the trio library should be used.
        """
        ...

    @property
    def frametime(self) -> float:
        """Time spent between the last frame and the current frame
        (in seconds).

        .. versionadded:: 1.8.0
        """
        ...

    @property
    def frames(self) -> int:
        """Number of internal frames (not necessarily drawn) from the start of
        the clock.

        .. versionadded:: 1.8.0
        """
        ...

    @property
    def frames_displayed(self) -> int:
        """Number of displayed frames from the start of the clock."""
        ...

    def usleep(self, microseconds) -> None:
        """Sleeps for the number of microseconds."""
        ...

    def idle(self) -> float:
        """(internal) waits here until the next frame."""
        ...

    async def async_idle(self) -> float:
        """(internal) async version of :meth:`idle`."""
        ...

    def tick(self) -> None:
        """Advance the clock to the next step. Must be called every frame.
        The default clock has a tick() function called by the core Kivy
        framework."""
        ...

    async def async_tick(self) -> None:
        """async version of :meth:`tick`."""
        ...

    def pre_idle(self) -> None:
        """Called before :meth:`idle` by :meth:`tick`."""
        ...

    def post_idle(self, ts, current) -> float:
        """Called after :meth:`idle` by :meth:`tick`."""
        ...

    def tick_draw(self) -> None:
        """Tick the drawing counter."""
        ...

    def get_fps(self) -> int | float:
        """Get the current average FPS calculated by the clock."""
        ...

    def get_rfps(self) -> int:
        """Get the current "real" FPS calculated by the clock.
        This counter reflects the real framerate displayed on the screen.

        In contrast to get_fps(), this function returns a counter of the
        number of frames, not the average of frames per second.
        """
        ...

    def get_time(self) -> float:
        """Get the last tick made by the clock."""
        ...

    def get_boottime(self) -> float:
        """Get the time in seconds from the application start."""
        ...

    time = ...
    def handle_exception(self, e) -> None: ...

class ClockBaseInterruptBehavior(ClockBaseBehavior):
    """A kivy clock which can be interrupted during a frame to execute events."""

    interupt_next_only = ...
    _event = ...
    _async_event = ...
    _get_min_timeout_func = ...
    def __init__(self, interupt_next_only=..., **kwargs) -> None: ...
    def init_async_lib(self, lib) -> None: ...
    def usleep(self, microseconds) -> None: ...
    async def async_usleep(self, microseconds) -> None: ...
    def on_schedule(self, event) -> None: ...
    def idle(self) -> float: ...
    async def async_idle(self) -> float: ...

class ClockBaseInterruptFreeBehavior(ClockBaseInterruptBehavior):
    """A base class for the clock that interrupts the sleep interval for
    free events.
    """
    def __init__(self, **kwargs) -> None: ...
    def on_schedule(self, event) -> None: ...

class ClockBase(ClockBaseBehavior, CyClockBase):
    """The ``default`` kivy clock. See module for details."""

    _sleep_obj = ...
    def __init__(self, **kwargs) -> None: ...
    def usleep(self, microseconds) -> None: ...

class ClockBaseInterrupt(ClockBaseInterruptBehavior, CyClockBase):
    """The ``interrupt`` kivy clock. See module for details."""

    ...

class ClockBaseFreeInterruptAll(ClockBaseInterruptFreeBehavior, CyClockBaseFree):
    """The ``free_all`` kivy clock. See module for details."""

    ...

class ClockBaseFreeInterruptOnly(ClockBaseInterruptFreeBehavior, CyClockBaseFree):
    """The ``free_only`` kivy clock. See module for details."""
    def idle(self) -> float: ...
    async def async_idle(self) -> float: ...

def mainthread[**P](func: Callable[P, object]) -> Callable[P, None]: ...

class TriggeredDecorator(Protocol):
    def __call__[**P](self, func: Callable[P, object]) -> Callable[P, None]: ...

def triggered(timeout: float = ..., interval: bool = ...) -> TriggeredDecorator: ...

if "KIVY_DOC_INCLUDE" in environ:
    Clock: ClockBase = ...
else:
    _classes = ...
    _clk = ...
    Clock: ClockBase = ...
