"""
Hand-written stub. `kivy.event` re-exports from the compiled `kivy._event`,
so pyright's stub generator produced only opaque assignments here.
"""

from collections.abc import Callable
from typing import Any

from kivy.properties import Property

__all__ = ("EventDispatcher", "ObjectWithUid", "Observable")

class ObjectWithUid:
    @property
    def uid(self) -> int: ...

class Observable(ObjectWithUid):
    def bind(self, **kwargs: Callable[..., Any]) -> None: ...
    def unbind(self, **kwargs: Callable[..., Any]) -> None: ...
    def fbind(
        self, name: str, func: Callable[..., Any], *largs: Any, **kwargs: Any
    ) -> int: ...
    def funbind(
        self, name: str, func: Callable[..., Any], *largs: Any, **kwargs: Any
    ) -> None: ...
    def unbind_uid(self, name: str, uid: int) -> None: ...

class EventDispatcher(ObjectWithUid):
    def __init__(self, **kwargs: Any) -> None: ...
    def register_event_type(self, event_type: str) -> None: ...
    def unregister_event_type(self, event_type: str) -> None: ...
    def is_event_type(self, event_type: str) -> bool: ...
    def bind(self, **kwargs: Callable[..., Any]) -> None: ...
    def unbind(self, **kwargs: Callable[..., Any]) -> None: ...
    def fbind(
        self, name: str, func: Callable[..., Any], *largs: Any, **kwargs: Any
    ) -> int: ...
    def funbind(
        self, name: str, func: Callable[..., Any], *largs: Any, **kwargs: Any
    ) -> None: ...
    def unbind_uid(self, name: str, uid: int) -> None: ...
    def dispatch(self, event_type: str, *largs: Any, **kwargs: Any) -> bool: ...
    def dispatch_generic(self, event_type: str, *largs: Any, **kwargs: Any) -> bool: ...
    def dispatch_children(
        self, event_type: str, *largs: Any, **kwargs: Any
    ) -> bool: ...
    def getter(self, name: str) -> Callable[[EventDispatcher], Any]: ...
    def setter(self, name: str) -> Callable[[EventDispatcher, Any], None]: ...
    def property(self, name: str, quiet: bool = False) -> Property[Any] | None: ...
    def properties(self) -> dict[str, Property[Any]]: ...
    def create_property(
        self,
        name: str,
        value: Any = None,
        default_value: bool = True,
        *largs: Any,
        **kwargs: Any,
    ) -> None: ...
    def apply_property(self, **kwargs: Property[Any]) -> None: ...
    def events(self) -> list[str]: ...
    @property
    def proxy_ref(self) -> Any: ...
